name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'
    - run: go version
    - run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o comms_windows_amd64
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o comms_linux_arm
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o comms_linux_arm64
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o comms_linux_amd64
        ./comms_linux_amd64 --version
