name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
    - run: go version
    - run: |
        GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o comms_linux_amd64
        ./comms_linux_amd64 --version
