name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
    - name: Build files
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags '-X "main.Version=${{ github.event.release.name }}"' -o comms_linux_amd64
        ./comms_linux_amd64 --version
    - name: Create checksums.txt
      run: |
        touch comms_${{ github.event.release.name }}_checksums.txt
        sha256sum comms_linux_amd64 >> comms_${{ github.event.release.name }}_checksums.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          comms_${{ github.event.release.name }}_checksums.txt
          comms_linux_amd64
          